name: legatus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.29+49

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  provider: ^6.0.3
  equatable: ^2.0.5
  flutter_screenutil: ^5.3.1
  persistent_bottom_nav_bar_v2: ^4.2.5
  mask_text_input_formatter: ^2.4.0
  date_time_format: ^2.0.1
  permission_handler: ^10.0.0
  geolocator: ^9.0.1
  uuid: ^3.0.6
  device_info_plus: ^4.1.2
  path_provider: ^2.0.11
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  flutter_slidable: ^2.0.0
  http_interceptor: ^1.0.2
  flutter_spinkit: ^5.1.0
  extended_image: ^6.2.1
  url_launcher: ^6.1.5
  json_patch: ^3.0.0
  share_plus: ^4.0.10+1
  wakelock: ^0.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  card_swiper: ^2.0.4
  fluttertoast: ^8.0.9
  flutter_video_info: ^1.2.0
  fijkplayer: ^0.10.1

  ####################
  camera: ^0.10.0+1
  native_device_orientation: ^1.1.4
  video_player: ^2.4.7
  path: ^1.8.1
  flutter_sound: ^9.2.13
  audio_session: ^0.1.10
  audioplayers: ^1.0.1
  intl: ^0.17.0
  ####################

  easy_localization: ^3.0.1
  # flutter pub run easy_localization:generate --source-dir ./lib/Assets/Langs
  # flutter pub run easy_localization:generate --source-dir ./lib/Assets/Langs -f keys -o locale_keys.g.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0
  # flutter pub run flutter_launcher_icons:main
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  # generate hive adapter file
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  

flutter_icons:
  android: true
  ios: true
  image_path_android: "lib/Assets/Images/logo-no-alpha.png"
  image_path_ios: "lib/Assets/Images/logo-no-alpha.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/Assets/Images/
    - lib/Assets/Langs/


  fonts:
    - family: Roboto
      fonts:
        - asset: lib/Assets/Fonts/Roboto-Regular.ttf
        - asset: lib/Assets/Fonts/Roboto-Italic.ttf
          style: italic
        - asset: lib/Assets/Fonts/Roboto-Thin.ttf
          weight: 100
        - asset: lib/Assets/Fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        # - asset: lib/Assets/Fonts/Roboto-ExtraLight.ttf
        #   weight: 200
        - asset: lib/Assets/Fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/Assets/Fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/Assets/Fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/Assets/Fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: lib/Assets/Fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/Assets/Fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        # - asset: lib/Assets/Fonts/Roboto-SemiBold.ttf
        #   weight: 600
        - asset: lib/Assets/Fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/Assets/Fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        # - asset: lib/Assets/Fonts/Roboto-ExtraBold.ttf
        #   weight: 800
        - asset: lib/Assets/Fonts/Roboto-Black.ttf
          weight: 900
        - asset: lib/Assets/Fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
